
weather.visualcrossing.url=https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/
weather.visualcrossing.key=FKSPHKHK4FJ7JS7V9BJS38869
# Create free account on https://www.visualcrossing.com/weather-data-editions and copy the key from `My Account` section

